GameLinkEnabled: FALSE
MIDlet-Version: 0.1.28
MIDlet-Info-URL: http://www.thqwireless.com
Manifest-Version: 1.0
Created-By: Metaflow
MicroEdition-Configuration: CLDC-1.0
MIDlet-Name: Prehistoric Tribes Bahasa Indonesia
MIDlet-Vendor: Red Wyvern
Cheat-Support: off
Content-Folder: Games
GameUrl-de: http://wap.thqwireless.com
MIDlet-Icon: /icon.png
GameUrl-es: http://wap.thqwireless.com
GameUrl-fr: http://wap.thqwireless.com
MIDlet-1: Prehistoric Tribes, icon.png, tribes
MicroEdition-Profile: MIDP-2.0
GameUrl-it: http://wap.thqwireless.com
GameUrl-en: http://wap.thqwireless.com
